### ISSUE TITLE
Enhancement: Markdown Features based on Docusaurus

### ISSUE THREAD

**Issue by RC-Lee** [rclee91/SiteGen#16]
With Docusaurus as a template, current markdown support for SiteGen is too basic, lacking many features.

- [X] Swap basic markdown support for full open source one.
- [ ] Apply syntax highlights to in block code (issue #18 )
- [ ] Markdown Front Matter support (issue #19 )
- [ ] MDX and React Component support (issue #20 )
- [ ] Admonitions (issue #21 )
- [ ] #23
